[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.build]
cmds = [
  "python -m venv venv",
  ". venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.start]
cmds = [
  ". venv/bin/activate",
  "python bot.py"
]
